/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl1.parser.antlr.internal.InternalEsportDslParser;
import org.xtext.example.mydsl1.services.EsportDslGrammarAccess;

public class EsportDslParser extends AbstractAntlrParser {

	@Inject
	private EsportDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEsportDslParser createParser(XtextTokenStream stream) {
		return new InternalEsportDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}

	public EsportDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EsportDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
