/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.esportDsl.ui.internal.EsportDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EsportDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EsportDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EsportDslActivator.getInstance().getInjector(EsportDslActivator.ORG_XTEXT_EXAMPLE_MYDSL1_ESPORTDSL);
	}
	
}
