/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EsportDslStandaloneSetup extends EsportDslStandaloneSetupGenerated {

	def static void doSetup() {
		new EsportDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
