/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEsportDslScopeProvider extends DelegatingScopeProvider {
}
