/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl1.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl1.ide.contentassist.antlr.internal.InternalEsportDslParser;
import org.xtext.example.mydsl1.services.EsportDslGrammarAccess;

public class EsportDslParser extends AbstractContentAssistParser {

	@Inject
	private EsportDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalEsportDslParser createParser() {
		InternalEsportDslParser result = new InternalEsportDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getRootAccess().getAlternatives(), "rule__Root__Alternatives");
					put(grammarAccess.getPersonAccess().getAlternatives(), "rule__Person__Alternatives");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getTournamentTypeAccess().getAlternatives(), "rule__TournamentType__Alternatives");
					put(grammarAccess.getMatchTypeAccess().getAlternatives(), "rule__MatchType__Alternatives");
					put(grammarAccess.getGroupStageTypeAccess().getAlternatives(), "rule__GroupStageType__Alternatives");
					put(grammarAccess.getSeasonAccess().getAlternatives(), "rule__Season__Alternatives");
					put(grammarAccess.getPositionAccess().getAlternatives(), "rule__Position__Alternatives");
					put(grammarAccess.getCapacityTypeAccess().getAlternatives(), "rule__CapacityType__Alternatives");
					put(grammarAccess.getZoneAccess().getGroup(), "rule__Zone__Group__0");
					put(grammarAccess.getZoneAccess().getGroup_6(), "rule__Zone__Group_6__0");
					put(grammarAccess.getZoneAccess().getGroup_8(), "rule__Zone__Group_8__0");
					put(grammarAccess.getZoneAccess().getGroup_8_2(), "rule__Zone__Group_8_2__0");
					put(grammarAccess.getTournamentAccess().getGroup(), "rule__Tournament__Group__0");
					put(grammarAccess.getTournamentAccess().getGroup_9(), "rule__Tournament__Group_9__0");
					put(grammarAccess.getTournamentAccess().getGroup_11(), "rule__Tournament__Group_11__0");
					put(grammarAccess.getTournamentAccess().getGroup_11_2(), "rule__Tournament__Group_11_2__0");
					put(grammarAccess.getTournamentAccess().getGroup_12(), "rule__Tournament__Group_12__0");
					put(grammarAccess.getTournamentAccess().getGroup_13(), "rule__Tournament__Group_13__0");
					put(grammarAccess.getTournamentAccess().getGroup_13_3(), "rule__Tournament__Group_13_3__0");
					put(grammarAccess.getTournamentAccess().getGroup_14(), "rule__Tournament__Group_14__0");
					put(grammarAccess.getTournamentAccess().getGroup_14_2(), "rule__Tournament__Group_14_2__0");
					put(grammarAccess.getTournamentAccess().getGroup_15(), "rule__Tournament__Group_15__0");
					put(grammarAccess.getTournamentAccess().getGroup_15_2(), "rule__Tournament__Group_15_2__0");
					put(grammarAccess.getLeagueAccess().getGroup(), "rule__League__Group__0");
					put(grammarAccess.getLeagueAccess().getGroup_8(), "rule__League__Group_8__0");
					put(grammarAccess.getLeagueAccess().getGroup_8_2(), "rule__League__Group_8_2__0");
					put(grammarAccess.getTeamAccess().getGroup(), "rule__Team__Group__0");
					put(grammarAccess.getTeamAccess().getGroup_8(), "rule__Team__Group_8__0");
					put(grammarAccess.getQualificationAccess().getGroup(), "rule__Qualification__Group__0");
					put(grammarAccess.getCountryAccess().getGroup(), "rule__Country__Group__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getFinalStageAccess().getGroup(), "rule__FinalStage__Group__0");
					put(grammarAccess.getFinalStageAccess().getGroup_6(), "rule__FinalStage__Group_6__0");
					put(grammarAccess.getFinalStageAccess().getGroup_8(), "rule__FinalStage__Group_8__0");
					put(grammarAccess.getFinalStageAccess().getGroup_8_3(), "rule__FinalStage__Group_8_3__0");
					put(grammarAccess.getGroupStageAccess().getGroup(), "rule__GroupStage__Group__0");
					put(grammarAccess.getGroupStageAccess().getGroup_7(), "rule__GroupStage__Group_7__0");
					put(grammarAccess.getGroupStageAccess().getGroup_7_2(), "rule__GroupStage__Group_7_2__0");
					put(grammarAccess.getMatchAccess().getGroup(), "rule__Match__Group__0");
					put(grammarAccess.getGroupAccess().getGroup(), "rule__Group__Group__0");
					put(grammarAccess.getGroupAccess().getGroup_5(), "rule__Group__Group_5__0");
					put(grammarAccess.getGroupAccess().getGroup_7(), "rule__Group__Group_7__0");
					put(grammarAccess.getGroupAccess().getGroup_7_2(), "rule__Group__Group_7_2__0");
					put(grammarAccess.getPlayerAccess().getGroup(), "rule__Player__Group__0");
					put(grammarAccess.getPlayerAccess().getGroup_8(), "rule__Player__Group_8__0");
					put(grammarAccess.getPlayerAccess().getGroup_8_2(), "rule__Player__Group_8_2__0");
					put(grammarAccess.getCoachAccess().getGroup(), "rule__Coach__Group__0");
					put(grammarAccess.getCoachAccess().getGroup_7(), "rule__Coach__Group_7__0");
					put(grammarAccess.getCoachAccess().getGroup_7_2(), "rule__Coach__Group_7_2__0");
					put(grammarAccess.getCapacityAccess().getGroup(), "rule__Capacity__Group__0");
					put(grammarAccess.getRootAccess().getZonesAssignment_0(), "rule__Root__ZonesAssignment_0");
					put(grammarAccess.getRootAccess().getTournamentsAssignment_1(), "rule__Root__TournamentsAssignment_1");
					put(grammarAccess.getRootAccess().getLeaguesAssignment_2(), "rule__Root__LeaguesAssignment_2");
					put(grammarAccess.getRootAccess().getTeamsAssignment_3(), "rule__Root__TeamsAssignment_3");
					put(grammarAccess.getRootAccess().getPersonsAssignment_4(), "rule__Root__PersonsAssignment_4");
					put(grammarAccess.getRootAccess().getQualificationsAssignment_5(), "rule__Root__QualificationsAssignment_5");
					put(grammarAccess.getRootAccess().getCountriesAssignment_6(), "rule__Root__CountriesAssignment_6");
					put(grammarAccess.getZoneAccess().getNameAssignment_2(), "rule__Zone__NameAssignment_2");
					put(grammarAccess.getZoneAccess().getCountriesAssignment_5(), "rule__Zone__CountriesAssignment_5");
					put(grammarAccess.getZoneAccess().getCountriesAssignment_6_1(), "rule__Zone__CountriesAssignment_6_1");
					put(grammarAccess.getZoneAccess().getTeamsAssignment_8_1(), "rule__Zone__TeamsAssignment_8_1");
					put(grammarAccess.getZoneAccess().getTeamsAssignment_8_2_1(), "rule__Zone__TeamsAssignment_8_2_1");
					put(grammarAccess.getTournamentAccess().getNameAssignment_2(), "rule__Tournament__NameAssignment_2");
					put(grammarAccess.getTournamentAccess().getSizeAssignment_4(), "rule__Tournament__SizeAssignment_4");
					put(grammarAccess.getTournamentAccess().getTypeAssignment_5(), "rule__Tournament__TypeAssignment_5");
					put(grammarAccess.getTournamentAccess().getYearAssignment_6(), "rule__Tournament__YearAssignment_6");
					put(grammarAccess.getTournamentAccess().getAllowedZonesAssignment_8(), "rule__Tournament__AllowedZonesAssignment_8");
					put(grammarAccess.getTournamentAccess().getAllowedZonesAssignment_9_1(), "rule__Tournament__AllowedZonesAssignment_9_1");
					put(grammarAccess.getTournamentAccess().getCountriesAssignment_11_1(), "rule__Tournament__CountriesAssignment_11_1");
					put(grammarAccess.getTournamentAccess().getCountriesAssignment_11_2_1(), "rule__Tournament__CountriesAssignment_11_2_1");
					put(grammarAccess.getTournamentAccess().getQualifiesForAssignment_12_1(), "rule__Tournament__QualifiesForAssignment_12_1");
					put(grammarAccess.getTournamentAccess().getQualifiesFromAssignment_13_2(), "rule__Tournament__QualifiesFromAssignment_13_2");
					put(grammarAccess.getTournamentAccess().getQualifiesFromAssignment_13_3_1(), "rule__Tournament__QualifiesFromAssignment_13_3_1");
					put(grammarAccess.getTournamentAccess().getFinalstagesAssignment_14_1(), "rule__Tournament__FinalstagesAssignment_14_1");
					put(grammarAccess.getTournamentAccess().getFinalstagesAssignment_14_2_1(), "rule__Tournament__FinalstagesAssignment_14_2_1");
					put(grammarAccess.getTournamentAccess().getGroupstagesAssignment_15_1(), "rule__Tournament__GroupstagesAssignment_15_1");
					put(grammarAccess.getTournamentAccess().getGroupstagesAssignment_15_2_1(), "rule__Tournament__GroupstagesAssignment_15_2_1");
					put(grammarAccess.getLeagueAccess().getNameAssignment_2(), "rule__League__NameAssignment_2");
					put(grammarAccess.getLeagueAccess().getSizeAssignment_4(), "rule__League__SizeAssignment_4");
					put(grammarAccess.getLeagueAccess().getYearAssignment_5(), "rule__League__YearAssignment_5");
					put(grammarAccess.getLeagueAccess().getSeasonAssignment_6(), "rule__League__SeasonAssignment_6");
					put(grammarAccess.getLeagueAccess().getZoneAssignment_7(), "rule__League__ZoneAssignment_7");
					put(grammarAccess.getLeagueAccess().getQualifiesForAssignment_8_1(), "rule__League__QualifiesForAssignment_8_1");
					put(grammarAccess.getLeagueAccess().getQualifiesForAssignment_8_2_1(), "rule__League__QualifiesForAssignment_8_2_1");
					put(grammarAccess.getLeagueAccess().getGroupstageAssignment_9(), "rule__League__GroupstageAssignment_9");
					put(grammarAccess.getTeamAccess().getNameAssignment_2(), "rule__Team__NameAssignment_2");
					put(grammarAccess.getTeamAccess().getChampionshipPointsAssignment_4(), "rule__Team__ChampionshipPointsAssignment_4");
					put(grammarAccess.getTeamAccess().getCoachAssignment_5(), "rule__Team__CoachAssignment_5");
					put(grammarAccess.getTeamAccess().getPlayersAssignment_7(), "rule__Team__PlayersAssignment_7");
					put(grammarAccess.getTeamAccess().getPlayersAssignment_8_1(), "rule__Team__PlayersAssignment_8_1");
					put(grammarAccess.getQualificationAccess().getNameAssignment_2(), "rule__Qualification__NameAssignment_2");
					put(grammarAccess.getCountryAccess().getNameAssignment_2(), "rule__Country__NameAssignment_2");
					put(grammarAccess.getFinalStageAccess().getMaxNbGamesAssignment_3(), "rule__FinalStage__MaxNbGamesAssignment_3");
					put(grammarAccess.getFinalStageAccess().getTeamsAssignment_5(), "rule__FinalStage__TeamsAssignment_5");
					put(grammarAccess.getFinalStageAccess().getTeamsAssignment_6_1(), "rule__FinalStage__TeamsAssignment_6_1");
					put(grammarAccess.getFinalStageAccess().getMatchsAssignment_8_2(), "rule__FinalStage__MatchsAssignment_8_2");
					put(grammarAccess.getFinalStageAccess().getMatchsAssignment_8_3_1(), "rule__FinalStage__MatchsAssignment_8_3_1");
					put(grammarAccess.getGroupStageAccess().getTypeAssignment_3(), "rule__GroupStage__TypeAssignment_3");
					put(grammarAccess.getGroupStageAccess().getMaxNbGamesAssignment_4(), "rule__GroupStage__MaxNbGamesAssignment_4");
					put(grammarAccess.getGroupStageAccess().getMeetingsInSameGroupAssignment_5(), "rule__GroupStage__MeetingsInSameGroupAssignment_5");
					put(grammarAccess.getGroupStageAccess().getMeetingsWithOtherGroupsAssignment_6(), "rule__GroupStage__MeetingsWithOtherGroupsAssignment_6");
					put(grammarAccess.getGroupStageAccess().getGroupsAssignment_7_1(), "rule__GroupStage__GroupsAssignment_7_1");
					put(grammarAccess.getGroupStageAccess().getGroupsAssignment_7_2_1(), "rule__GroupStage__GroupsAssignment_7_2_1");
					put(grammarAccess.getMatchAccess().getTypeAssignment_3(), "rule__Match__TypeAssignment_3");
					put(grammarAccess.getMatchAccess().getLoserWinsAssignment_4(), "rule__Match__LoserWinsAssignment_4");
					put(grammarAccess.getMatchAccess().getTeamWinnerAssignment_5(), "rule__Match__TeamWinnerAssignment_5");
					put(grammarAccess.getMatchAccess().getTeamLoserAssignment_6(), "rule__Match__TeamLoserAssignment_6");
					put(grammarAccess.getGroupAccess().getTeamsAssignment_4(), "rule__Group__TeamsAssignment_4");
					put(grammarAccess.getGroupAccess().getTeamsAssignment_5_1(), "rule__Group__TeamsAssignment_5_1");
					put(grammarAccess.getGroupAccess().getMatchsAssignment_7_1(), "rule__Group__MatchsAssignment_7_1");
					put(grammarAccess.getGroupAccess().getMatchsAssignment_7_2_1(), "rule__Group__MatchsAssignment_7_2_1");
					put(grammarAccess.getPlayerAccess().getNameAssignment_2(), "rule__Player__NameAssignment_2");
					put(grammarAccess.getPlayerAccess().getAgeAssignment_4(), "rule__Player__AgeAssignment_4");
					put(grammarAccess.getPlayerAccess().getCountryAssignment_5(), "rule__Player__CountryAssignment_5");
					put(grammarAccess.getPlayerAccess().getPositionAssignment_6(), "rule__Player__PositionAssignment_6");
					put(grammarAccess.getPlayerAccess().getDescriptionAssignment_7(), "rule__Player__DescriptionAssignment_7");
					put(grammarAccess.getPlayerAccess().getCapacitiesAssignment_8_1(), "rule__Player__CapacitiesAssignment_8_1");
					put(grammarAccess.getPlayerAccess().getCapacitiesAssignment_8_2_1(), "rule__Player__CapacitiesAssignment_8_2_1");
					put(grammarAccess.getCoachAccess().getNameAssignment_2(), "rule__Coach__NameAssignment_2");
					put(grammarAccess.getCoachAccess().getAgeAssignment_4(), "rule__Coach__AgeAssignment_4");
					put(grammarAccess.getCoachAccess().getCountryAssignment_5(), "rule__Coach__CountryAssignment_5");
					put(grammarAccess.getCoachAccess().getDescriptionAssignment_6(), "rule__Coach__DescriptionAssignment_6");
					put(grammarAccess.getCoachAccess().getCapacitiesAssignment_7_1(), "rule__Coach__CapacitiesAssignment_7_1");
					put(grammarAccess.getCoachAccess().getCapacitiesAssignment_7_2_1(), "rule__Coach__CapacitiesAssignment_7_2_1");
					put(grammarAccess.getCapacityAccess().getTypeAssignment_3(), "rule__Capacity__TypeAssignment_3");
					put(grammarAccess.getCapacityAccess().getValueAssignment_4(), "rule__Capacity__ValueAssignment_4");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public EsportDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EsportDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
